on: [push]

name: rust

jobs:
  main:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - uses: rui314/setup-mold@v1

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - run: rustup component add clippy

      - name: Run Clippy 
        uses: qernal/github-actions-rust-clippy@v2.0.2

      - name: Run Clippy (All Features)
        uses: qernal/github-actions-rust-clippy@v2.0.2
        with:
          args: "--all-features"
     
      - name: Run Clippy (default_no_std)
        uses: qernal/github-actions-rust-clippy@v2.0.2
        with:
          args: "--no-default-features,--features=default_no_std"

      - name: Run Clippy (--no-default-features)
        uses: qernal/github-actions-rust-clippy@v2.0.2
        with:
          args: "--no-default-features"
     