on: [push]

name: rust

jobs:
  main:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - uses: rui314/setup-mold@v1

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          override: true

      - run: rustup component add clippy

      - name: Run Clippy (All Features)
        if: always()
        run: cargo clippy --all-features

      - name: Run Clippy (no-std)
        if: always()
        run: cargo clippy --no-default-features --features=default_no_std

      - name: Run Clippy (No Default Features)
        if: always()
        run: cargo clippy --no-default-features
